### ISSUE TITLE
R48 Game Modes BF4.def

### ISSUE THREAD

**Issue by LumPenPacK** [Myrcon/Procon-1#168]
Here are the new game modes. Source: R48 Documentation 

http://battlelog.battlefield.com/bf4/forum/threadview/2979150494133084029/last/

procon.protected.maps.add "SquadObliteration0" "MP_Abandoned" "Squad Obliteration" "Zavod 311" 0
procon.protected.maps.add "Squad Obliteration" "MP_Journey" "Squad Obliteration" "Golmud Railway" 0
procon.protected.maps.add "SquadObliteration0" "MP_Naval" "Squad Obliteration" "Paracel Storm" 0
procon.protected.maps.add "SquadObliteration0" "MP_Prison" "Squad Obliteration" "Operation Locker" 0
procon.protected.maps.add "SquadObliteration0" "MP_Resort" "Squad Obliteration" "Hainan Resort" 0
procon.protected.maps.add "SquadObliteration0" "MP_Siege" "Squad Obliteration" "Siege of Shanghai" 0
procon.protected.maps.add "SquadObliteration0" "MP_Tremors" "Squad Obliteration" "Dawnbreaker" 0

**Comment by MorpheusXAUT** [comment]
Do you happen to know how many teams there will be?
I'm going to assume it's two teams with 5 people for know.

**Comment by LumPenPacK** [comment]
There are two teams.
The game mode is designed for up to 10 + (4) players
(Source: R48 Documentation BF4 PC Maps and Game Modes.pdf)

But you can run this game mode with any server size.

**Comment by MorpheusXAUT** [comment]
Update has been pushed to the repository server as well and should be distributed.
