### ISSUE TITLE
Issue with damageType in BFHL.def

### ISSUE THREAD

**Issue by EBassie** [Myrcon/Procon-1#171]
BF Hardline has new player classes:
Operator, Enforcer, Mechanic & Professional

I added all player classes to the BFHL.def with the weapon definitions, but there now seems to be a problem with Procon not handling those types well in the plugin interface.

List<string>(GetWeaponList(DamageTypes.Operator));
'PRoCon.Core.Players.Items.DamageTypes' does not contain a definition for 'Operator'

Reported here:
https://forum.myrcon.com/showthread.php?8070-Battlefield-Hardline-Procon&p=118759&viewfull=1#post118759

**Comment by EBassie** [comment]
OK... never mind. Learned there are is a default set we cannot get around.
Changed the damagetypes in the BFHL.def to use the the values used in:
https://github.com/Myrcon/Procon-1/blob/master/src/PRoCon.Core/Players/Items/Kits.cs

**Comment by ColColonCleaner** [comment]
Not sure I understand what the issue was here. Explain?

**Comment by EBassie** [comment]
The problem was explained by Tim on the Procon forums, see link above in original post.
The BFHL.def contained DamageType values onsupported by Procon.
