### ISSUE TITLE
Round timer should pause when round end event is detected

### ISSUE THREAD

**Issue by ColColonCleaner** [Myrcon/Procon-1#172]
Would be nice to see this fix.

**Comment by Phil-K** [comment]
Round timer is a visualization of the round timer send by the server in the serverInfo response.
So with every response it is updated to what the server has send.

**Comment by ColColonCleaner** [comment]
Not true. The UI artificially increments the timer every second while waiting on the next server info response, and continues to do this after round end, thus making the time invalid.

Why close this issue?

**Comment by Phil-K** [comment]
Do me a favor.
Take a look and quote the serverInfo lines directly after a round end event.
Does it have a round timer value?

**Comment by Phil-K** [comment]
Furthermore there is no onRoundStart event or equal which can be used reliable
to detect a round start. Keep in mind onLevelLoaded says nothing about pre-round,
ready-user, minRoundStart and so on. It just signals the level has loaded and
a round might start soon based on the parameter to start a round.

To include a "first kill might signal a round has started"-magic is not the way to have
in procon. If you need a round end / round start signal for / in your plugin it's best
to do this fuzzy magic there.

In case the round timer stays 0 in serverInfo response it will stay 0 in procon
based on the serverInfo update interval, which can mean you see a 0 every
30 seconds. May be you want to detect this "cycle of resets".

**Comment by ColColonCleaner** [comment]
I think you misunderstood what I was referring to, I'm not talking about plugin logic handling round state. **I'm talking about the round timer on the Procon UI.** It artificially adds time between the serverInfo events to show an estimate of what the actual round time is. This is a great feature, instead of waiting 30 seconds between visual updates of round time. **Unfortunately it continues to do this artificial adding after the round has ended.**

I'll find the lines causing this tonight once i'm home :)

**Comment by ColColonCleaner** [comment]
uscServerConnection:961

this.m_prcConnection.CurrentServerInfo.RoundTime++

Round time is artificially incremented even after round ends.

**Comment by ColColonCleaner** [comment]
Update on this?

**Comment by ColColonCleaner** [comment]
So, this just being ignored then?
