### ISSUE TITLE
BFHL.def typo, TurfwareLarge0

### ISSUE THREAD

**Issue by PapaCharlie9** [Myrcon/Procon-1#175]
````
[10:40:47] serverInfo
[10:40:48] OK Procon Test Server - HEIST ALL MAPS - myrcon.com 0 64 TurfWarLarge0 MP_Downtown 0 1 2 600 600 0  true true false 63610 1425 85.114.157.68:27015  true EU ams DE 0 IN_GAME
````

The BFHL docs also use "TurfWarLarge0".

Note that BFHL.def uses "TurfwarLarge0". 

This was first reported as a problem with MULTIbalancer not using settings for Conquest Large. This is because I'm using exact match for mode names.

I wasn't able to create a clean Pull Request, I've added too much cruft to my fork. I also couldn't figure out how to make a new fork without having to make a new Github account, so meh. I just attached a ZIP to the forum post here:

https://forum.myrcon.com/showthread.php?10223-BFHL-TurfwarLarge0-does-not-match-serverInfo-TurfWarLarge0

**Comment by EBassie** [comment]
Updated BFHL.def

**Comment by PapaCharlie9** [comment]
Somehow one got missed. It is correct in the ZIP version I sent, but didn't make it in the integration?

procon.protected.teamnames.add "MP_Desert05" 0 "global.conquest.neutral" "" "TurfwarLarge0"

**Comment by EBassie** [comment]
Also fixed that entry. Thanks.
