### ISSUE TITLE
Bf4 Def, little mistake

### ISSUE THREAD

**Issue by ChaT0n** [Myrcon/Procon-1#181]
In the BF4 definition file, on line 808  there is a small mistake:

procon.protected.maps.add "ConquestSmall0" "MP_CMP" "Conquest Large" "Operation Outbreak" 0

should be

procon.protected.maps.add "ConquestSmall0" "MP_CMP" "Conquest Small" "Operation Outbreak" 0

**Comment by ChaT0n** [comment]
fixed

**Comment by ColColonCleaner** [comment]
Wait, you fixed it in the procon release? What?

**Comment by MorpheusXAUT** [comment]
I assume he's talking about 840758d by EBassie, which fixes the reported issue.

**Comment by ChaT0n** [comment]
Yes , it was that one [840758d](https://github.com/Myrcon/Procon-1/commit/840758de0ac7ac2c5536fa067e5d1bbd0e2d4ae7)
