### ISSUE TITLE
Typo in bf4.def for new Dragon Valley

### ISSUE THREAD

**Issue by antivanity** [Myrcon/Procon-1#183]
// XP7 (Legacy Operations)
procon.protected.teamnames.add "XP7_Valley" 0 "global.tdm.neutral" "" "TeamDeathMatch1"
procon.protected.teamnames.add "XP7_Valley" 1 "global.tdm.us" "us.png" "TeamDeathMatch1"
procon.protected.teamnames.add "XP7_Valley" 2 "global.tdm.cn" "cn.png" "TeamDeathMatch1"

These lines, the TeamDeathMatch1 should be TeamDeathMatch0

**Comment by EBassie** [comment]
Thanks for reporting. Fixed.

**Comment by Phil-K** [comment]
Good Morning,

 

did you upload that change?

On GitHub I only see the last one changing the Timestamp in the header…

 

Greets

Phil.

**Comment by hubertott** [comment]
The commit before it had the fix, as far as I am aware.

If it's still missing something let me know.

**Comment by EBassie** [comment]
I had already  fixed that typo, so I closed the issue.

**Comment by Phil-K** [comment]
Ah, okay.

I was irritated by the date/time stamp of the emails.

They were a bit time traveling like. ;)
